#########################################################
# You must re-run configure.py after changing this file #
#########################################################

# Paths relative to src/
os/OSLink.c:
  .text: [0x8007136C, 0x80071d58]
  .data: [0x8010cb10, 0x8010cb60]

